# Generated by Django 5.2.17 on 2026-09-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(help_text="Section label shown above the title, e.g. 'Developer Journal'.", max_length=100)),
                ('excerpt', models.TextField(help_text='Short teaser shown on the listing page.')),
                ('image', models.ImageField(help_text='Illustration shown alongside the article.', upload_to='articles/', verbose_name='Article image')),
                ('image_alt', models.CharField(help_text='Accessible description of the article image.', max_length=255, verbose_name='Article image alt text')),
                ('page_reference', models.PositiveIntegerField(default=1, help_text="Page number shown in the 'Read more on page X' link.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the position of the article in the listing (lower shows first).')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
