# Generated by Django 5.2.17 on 2026-09-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_fix_seeded_image_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='page_reference',
        ),
    ]
