# Generated by Django 5.2.17 on 2026-09-12 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_category_model_and_taggit_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='order',
        ),
    ]
